# Generated by Django 6.0.3 on 2026-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_acts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('EMBAUCHE', "A l'embauche"), ('PERIODIQUE', 'Periodique'), ('REPRISE', 'Reprise de travail'), ('SPONTANEE', 'Spontanee'), ('DEPART', 'Depart')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visit', to='medical_acts.clinicalencounter')),
                ('vital_signs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_acts.vitalsigns')),
            ],
            options={
                'verbose_name': 'Visite medicale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AptitudeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude', models.CharField(choices=[('APT', 'Apte'), ('APT_R', 'Apte avec restrictions'), ('TEMP_INAPT', 'Inapte temporaire'), ('INAPT', 'Inapte')], max_length=15)),
                ('restrictions', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medical_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_certificate', to='medical_visits.medicalvisit')),
            ],
            options={
                'verbose_name': "Bulletin d'aptitude",
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardiovascular', models.TextField(blank=True)),
                ('respiratory', models.TextField(blank=True)),
                ('abdominal', models.TextField(blank=True)),
                ('neurological', models.TextField(blank=True)),
                ('musculoskeletal', models.TextField(blank=True)),
                ('skin_examination', models.TextField(blank=True)),
                ('ent_examination', models.TextField(blank=True)),
                ('ophthalmological', models.TextField(blank=True)),
                ('dental_notes', models.TextField(blank=True)),
                ('other_findings', models.TextField(blank=True)),
                ('medical_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_exam', to='medical_visits.medicalvisit')),
            ],
            options={
                'verbose_name': 'Examen physique',
            },
        ),
        migrations.CreateModel(
            name='UrineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.CharField(choices=[('ABSENT', 'Absent'), ('TRACES', 'Traces'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='ABSENT', max_length=10)),
                ('proteins', models.CharField(choices=[('ABSENT', 'Absent'), ('TRACES', 'Traces'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='ABSENT', max_length=10)),
                ('blood', models.CharField(choices=[('ABSENT', 'Absent'), ('TRACES', 'Traces'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='ABSENT', max_length=10)),
                ('leukocytes', models.CharField(choices=[('ABSENT', 'Absent'), ('TRACES', 'Traces'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='ABSENT', max_length=10)),
                ('nitrites', models.CharField(choices=[('POS', 'Positif'), ('NEG', 'Negatif')], default='NEG', max_length=5)),
                ('ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('specific_gravity', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('medical_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urine_exam', to='medical_visits.medicalvisit')),
            ],
            options={
                'verbose_name': 'Examen des urines',
            },
        ),
    ]
