# Generated by Django 6.0.3 on 2026-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_visits', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_date', models.DateField()),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('VALIDATED', 'Validé'), ('ABNORMAL', 'Anormal')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='explorations/')),
                ('medical_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explorations', to='medical_visits.medicalvisit')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explorations_done', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explorations_validated', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explorations', to='workers.worker')),
            ],
            options={
                'verbose_name': "Résultat d'exploration",
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='ECGResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('rhythm', models.CharField(blank=True, max_length=100)),
                ('pr_interval_ms', models.IntegerField(blank=True, null=True)),
                ('qrs_duration_ms', models.IntegerField(blank=True, null=True)),
                ('qt_interval_ms', models.IntegerField(blank=True, null=True)),
                ('axis_degrees', models.IntegerField(blank=True, null=True)),
                ('interpretation', models.CharField(choices=[('NORMAL', 'Normal'), ('SINUS_TACHY', 'Tachycardie sinusale'), ('SINUS_BRADY', 'Bradycardie sinusale'), ('AF', 'Fibrillation auriculaire'), ('BBB', 'Bloc de branche'), ('LVH', 'Hypertrophie VG'), ('OTHER', 'Autre')], default='NORMAL', max_length=15)),
                ('interpretation_text', models.TextField(blank=True)),
                ('machine_used', models.CharField(blank=True, max_length=100)),
                ('exploration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecg', to='explorations.explorationresult')),
            ],
            options={
                'verbose_name': 'ECG',
            },
        ),
        migrations.CreateModel(
            name='AudiometryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear', models.CharField(choices=[('LEFT', 'Gauche'), ('RIGHT', 'Droite'), ('BILATERAL', 'Bilatéral')], default='BILATERAL', max_length=10)),
                ('thresholds_right', models.JSONField(default=dict, help_text='{500:dB, 1000:dB, 2000:dB, 4000:dB, 8000:dB}')),
                ('thresholds_left', models.JSONField(default=dict)),
                ('interpretation', models.CharField(choices=[('NORMAL', 'Normal'), ('MILD', 'Léger'), ('MODERATE', 'Modéré'), ('SEVERE', 'Sévère'), ('PROFOUND', 'Profond')], default='NORMAL', max_length=15)),
                ('scotoma_notch', models.BooleanField(default=False, help_text='Encoche 4kHz (surdité professionnelle)')),
                ('exploration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiometry', to='explorations.explorationresult')),
            ],
            options={
                'verbose_name': 'Audiométrie',
            },
        ),
        migrations.CreateModel(
            name='SpirometryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fvc_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fev1_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fev1_fvc_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pef_liters_s', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pre_bronchodilator', models.BooleanField(default=True)),
                ('interpretation', models.CharField(choices=[('NORMAL', 'Normal'), ('OBS', 'Obstruction'), ('REST', 'Restriction'), ('MIXED', 'Mixte')], default='NORMAL', max_length=10)),
                ('severity', models.CharField(choices=[('MILD', 'Léger'), ('MODERATE', 'Modéré'), ('SEVERE', 'Sévère'), ('NA', 'N/A')], default='NA', max_length=15)),
                ('exploration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spirometry', to='explorations.explorationresult')),
            ],
            options={
                'verbose_name': 'Spirométrie',
            },
        ),
        migrations.CreateModel(
            name='VisionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_eye_distance', models.CharField(blank=True, max_length=20)),
                ('left_eye_distance', models.CharField(blank=True, max_length=20)),
                ('right_eye_near', models.CharField(blank=True, max_length=20)),
                ('left_eye_near', models.CharField(blank=True, max_length=20)),
                ('color_vision', models.CharField(choices=[('NORMAL', 'Normal'), ('DALTONISME', 'Daltonisme'), ('OTHER', 'Autre')], default='NORMAL', max_length=20)),
                ('depth_perception', models.BooleanField(default=True)),
                ('requires_correction', models.BooleanField(default=False)),
                ('correction_type', models.CharField(choices=[('NONE', 'Aucune'), ('GLASSES', 'Lunettes'), ('CONTACTS', 'Lentilles')], default='NONE', max_length=20)),
                ('exploration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vision_test', to='explorations.explorationresult')),
            ],
            options={
                'verbose_name': 'Visiotest',
            },
        ),
    ]
