# Generated by Django 6.0.3 on 2026-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_date', models.DateField(db_index=True)),
                ('encounter_time', models.TimeField()),
                ('encounter_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('MEDICAL_VISIT', 'Visite médicale'), ('OBSERVATION', 'Mise en observation'), ('EMERGENCY', 'Urgence'), ('ACT', 'Acte infirmier')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('COMPLETED', 'Complété'), ('VALIDATED', 'Validé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_as_nurse', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Rencontre clinique',
                'ordering': ['-encounter_date', '-encounter_time'],
            },
        ),
        migrations.CreateModel(
            name='Dressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_location', models.CharField(max_length=200)),
                ('wound_type', models.CharField(max_length=100)),
                ('wound_size_cm', models.CharField(blank=True, max_length=50)),
                ('dressing_type', models.CharField(max_length=100)),
                ('products_used', models.TextField(blank=True)),
                ('next_dressing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dressings', to='medical_acts.clinicalencounter')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dressings_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pansement',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medications', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medical_acts.clinicalencounter')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médicament',
                'ordering': ['drug_name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('DISCHARGED', 'Sorti'), ('REFERRED', 'Référé'), ('HOSPITALIZED', 'Hospitalisé')], max_length=15, null=True)),
                ('referred_to', models.TextField(blank=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='medical_acts.clinicalencounter')),
            ],
            options={
                'verbose_name': 'Observation',
            },
        ),
        migrations.CreateModel(
            name='RapidDiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('MALARIA', 'Paludisme'), ('HIV', 'VIH'), ('HEP_B', 'Hépatite B'), ('HEP_C', 'Hépatite C'), ('SYPHILIS', 'Syphilis'), ('GLYCEMIA', 'Glycémie'), ('OTHER', 'Autre')], max_length=15)),
                ('test_name', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('POSITIVE', 'Positif'), ('NEGATIVE', 'Négatif'), ('INVALID', 'Invalide'), ('PENDING', 'En attente')], default='PENDING', max_length=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdts', to='medical_acts.clinicalencounter')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdts_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TDR',
                'verbose_name_plural': 'Tests de diagnostic rapide',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='medical_acts.clinicalencounter')),
            ],
            options={
                'verbose_name': 'Constantes',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['worker', 'encounter_date'], name='medical_act_worker__a7d1dd_idx'),
        ),
    ]
