# Generated by Django 6.0.3 on 2026-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('task_list', models.JSONField(default=list, help_text='List of tasks with frequency and posture')),
                ('tools_equipment', models.TextField(blank=True)),
                ('work_environment', models.TextField(blank=True)),
                ('work_schedule', models.TextField(blank=True)),
                ('physical_risks', models.JSONField(default=list)),
                ('chemical_risks', models.JSONField(default=list)),
                ('biological_risks', models.JSONField(default=list)),
                ('ergonomic_risks', models.JSONField(default=list)),
                ('psychosocial_risks', models.JSONField(default=list)),
                ('overall_risk_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_sheets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_sheets', to='workers.jobposition')),
            ],
            options={
                'verbose_name': 'Fiche de poste',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('identified_risks', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='job_visits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_reports', to='workers.jobposition')),
                ('visited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_visits_done', to=settings.AUTH_USER_MODEL)),
                ('workers_present', models.ManyToManyField(blank=True, to='workers.worker')),
            ],
            options={
                'verbose_name': 'Rapport de visite de poste',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('TEST', 'Test'), ('AWARENESS', 'Sensibilisation'), ('TRAINING', 'Formation'), ('JOB_VISIT', 'Visite de poste'), ('INSPECTION', 'Inspection'), ('COVERAGE', 'Couverture medicale')], max_length=15)),
                ('title', models.CharField(max_length=300)),
                ('activity_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('participants_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workers_involved', models.ManyToManyField(blank=True, to='workers.worker')),
            ],
            options={
                'verbose_name': 'Activite du service medical',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialMedicalSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('NOISE', 'Bruit'), ('CHEMICAL', 'Chimique'), ('RADIATION', 'Rayonnement'), ('BIOLOGICAL', 'Biologique'), ('DUST', 'Poussiere'), ('ERGONOMIC', 'Ergonomique'), ('OTHER', 'Autre')], max_length=15)),
                ('risk_agent', models.CharField(max_length=200)),
                ('started_date', models.DateField()),
                ('review_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency_months', models.IntegerField(default=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('ENDED', 'Terminee')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_list', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Surveillance medicale speciale',
                'ordering': ['review_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('NOISE', 'Bruit'), ('CHEMICAL', 'Chimique'), ('RADIATION', 'Rayonnement'), ('BIOLOGICAL', 'Biologique'), ('DUST', 'Poussiere'), ('ERGONOMIC', 'Ergonomique'), ('PHYSICAL', 'Physique'), ('PSYCHOSOCIAL', 'Psychosocial'), ('OTHER', 'Autre')], max_length=15)),
                ('risk_agent', models.CharField(max_length=200)),
                ('risk_level', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Eleve'), (4, 'Tres eleve')], default=1)),
                ('preventive_measures', models.TextField(blank=True)),
                ('ppe_required', models.TextField(blank=True)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_risks', to='workers.jobposition')),
            ],
            options={
                'verbose_name': 'Risque professionnel',
                'ordering': ['-risk_level'],
            },
        ),
    ]
