# Generated by Django 6.0.3 on 2026-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_acts', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('disease_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('personal_history', models.TextField(blank=True)),
                ('physical_exam_findings', models.TextField(blank=True)),
                ('systems_review', models.JSONField(blank=True, default=dict)),
                ('working_diagnosis', models.TextField(blank=True)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('treatment_plan', models.TextField(blank=True)),
                ('referral_needed', models.BooleanField(default=False)),
                ('referral_note', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('sick_leave_days', models.IntegerField(blank=True, null=True)),
                ('work_restriction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='medical_acts.clinicalencounter')),
                ('vital_signs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_acts.vitalsigns')),
            ],
            options={
                'verbose_name': 'Consultation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateField()),
                ('declaration_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=300)),
                ('circumstance', models.TextField()),
                ('body_part_injured', models.CharField(max_length=200)),
                ('injury_type', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('MINOR', 'Benin'), ('MODERATE', 'Modere'), ('SEVERE', 'Grave'), ('FATAL', 'Fatal')], default='MINOR', max_length=10)),
                ('lost_work_days', models.IntegerField(default=0)),
                ('return_to_work_date', models.DateField(blank=True, null=True)),
                ('is_recognized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_accidents', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Accident de travail',
                'ordering': ['-accident_date'],
            },
        ),
    ]
