# Generated by Django 6.0.3 on 2026-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('CUSTOM', 'Personnalise')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], default='PDF', max_length=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('GENERATING', 'Generation'), ('READY', 'Pret'), ('FAILED', 'Echec')], default='PENDING', max_length=15)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport genere',
                'ordering': ['-generated_at'],
            },
        ),
    ]
